version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - "9091:9091"
#    depends_on:
#      - db
    environment:
      - CONFIG_ENV=${CONFIG_ENV}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - SERVER_PORT=${SERVER_PORT}

#  db:
#    image: postgres:14
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: myapp
#    ports:
#      - "5432:5432"
#    volumes:
#      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
