version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "82:8080"
      - "9091:9091"
#    depends_on:
#      - db
    environment:
      - CONFIG_ENV=env
      - DB_PATH=/app/db/data.sqlite
      - SERVER_PORT=8080
    volumes:
      - ./db/data.sqlite:/app/db/data.sqlite

#  db:
#    image: postgres:14
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: myapp
#    ports:
#      - "5432:5432"
#    volumes:
#      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
